
/**
 * @file check_node.c
 *
 * Functions needed by chkm traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: check_node.c.xsl 15657 2007-11-13 13:57:30Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup check Touch all Tree Functions to catch every node, son and attribute
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "check_node.h"
#include "check_attribs.h"
#include "tree_basic.h"
#include "traverse.h"
#include "dbug.h"

#define CHKMTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define CHKMCOND( node, info)                                    \
    ? CHKMTRAV( node, info)                                      \
    : (node)



/*******************************************************************************
 *
 * @fn CHKMpostfun
 *
 * This is the postfun function of the CHKM Traversal  
 *
 ******************************************************************************/
node *
CHKMpostfun (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMpostfun");

  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMassign
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMassign (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMassign");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  ASSIGN_NAME (arg_node) =
    CHKMattribString (ASSIGN_NAME (arg_node), arg_info);
  ASSIGN_EXPRESSION (arg_node) =
    CHKMTRAV (ASSIGN_EXPRESSION (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMbinop
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMbinop (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMbinop");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  BINOP_LEFT (arg_node) = CHKMTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (arg_node) = CHKMTRAV (BINOP_RIGHT (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMblock
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Block node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMblock (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMblock");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  BLOCK_NEXT (arg_node) = CHKMTRAV (BLOCK_NEXT (arg_node), arg_info);
  BLOCK_THIS (arg_node) = CHKMTRAV (BLOCK_THIS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMboolconst
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node BoolConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMboolconst (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMboolconst");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMcast
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMcast (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMcast");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  CAST_EXPRESSION (arg_node) =
    CHKMTRAV (CAST_EXPRESSION (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMdecblock
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node DecBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMdecblock (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMdecblock");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  DECBLOCK_NEXT (arg_node) = CHKMTRAV (DECBLOCK_NEXT (arg_node), arg_info);
  DECBLOCK_THIS (arg_node) = CHKMTRAV (DECBLOCK_THIS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMdowhile
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMdowhile (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMdowhile");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  DOWHILE_CONDITION (arg_node) =
    CHKMTRAV (DOWHILE_CONDITION (arg_node), arg_info);
  DOWHILE_BODY (arg_node) = CHKMTRAV (DOWHILE_BODY (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfloatconst
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FloatConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfloatconst (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfloatconst");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfor
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfor (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfor");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FOR_START (arg_node) = CHKMTRAV (FOR_START (arg_node), arg_info);
  FOR_STOP (arg_node) = CHKMTRAV (FOR_STOP (arg_node), arg_info);
  FOR_STEP (arg_node) = CHKMTRAV (FOR_STEP (arg_node), arg_info);
  FOR_BODY (arg_node) = CHKMTRAV (FOR_BODY (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfunargs
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunArgs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfunargs (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfunargs");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNARGS_NEXT (arg_node) = CHKMTRAV (FUNARGS_NEXT (arg_node), arg_info);
  FUNARGS_THIS (arg_node) = CHKMTRAV (FUNARGS_THIS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfunbody
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfunbody (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfunbody");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNBODY_DECLARATIONS (arg_node) =
    CHKMTRAV (FUNBODY_DECLARATIONS (arg_node), arg_info);
  FUNBODY_STATEMENTS (arg_node) =
    CHKMTRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfuncall
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfuncall (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfuncall");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNCALL_NAME (arg_node) =
    CHKMattribString (FUNCALL_NAME (arg_node), arg_info);
  FUNCALL_ARGS (arg_node) = CHKMTRAV (FUNCALL_ARGS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfundec
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfundec (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfundec");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNDEC_NAME (arg_node) =
    CHKMattribString (FUNDEC_NAME (arg_node), arg_info);
  FUNDEC_PARAMS (arg_node) = CHKMTRAV (FUNDEC_PARAMS (arg_node), arg_info);
  FUNDEC_BODY (arg_node) = CHKMTRAV (FUNDEC_BODY (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfunparam
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunParam node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfunparam (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfunparam");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNPARAM_NAME (arg_node) =
    CHKMattribString (FUNPARAM_NAME (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMfunparams
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node FunParams node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMfunparams (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMfunparams");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  FUNPARAMS_NEXT (arg_node) = CHKMTRAV (FUNPARAMS_NEXT (arg_node), arg_info);
  FUNPARAMS_THIS (arg_node) = CHKMTRAV (FUNPARAMS_THIS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMif
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMif (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMif");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  IF_CONDITION (arg_node) = CHKMTRAV (IF_CONDITION (arg_node), arg_info);
  IF_THEN (arg_node) = CHKMTRAV (IF_THEN (arg_node), arg_info);
  IF_ELSE (arg_node) = CHKMTRAV (IF_ELSE (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMintconst
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node IntConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMintconst (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMintconst");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMmodule
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMmodule (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMmodule");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  MODULE_NAME (arg_node) =
    CHKMattribString (MODULE_NAME (arg_node), arg_info);
  MODULE_DECLARATIONS (arg_node) =
    CHKMTRAV (MODULE_DECLARATIONS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMmonop
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMmonop (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMmonop");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  MONOP_OPERAND (arg_node) = CHKMTRAV (MONOP_OPERAND (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMproccall
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node ProcCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMproccall (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMproccall");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  PROCCALL_NAME (arg_node) =
    CHKMattribString (PROCCALL_NAME (arg_node), arg_info);
  PROCCALL_ARGS (arg_node) = CHKMTRAV (PROCCALL_ARGS (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMreturn
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMreturn (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMreturn");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  RETURN_EXPRESSION (arg_node) =
    CHKMTRAV (RETURN_EXPRESSION (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMvardec
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMvardec (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMvardec");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  VARDEC_NAME (arg_node) =
    CHKMattribString (VARDEC_NAME (arg_node), arg_info);
  VARDEC_EXPRESSION (arg_node) =
    CHKMTRAV (VARDEC_EXPRESSION (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMvariable
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node Variable node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMvariable (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMvariable");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  VARIABLE_NAME (arg_node) =
    CHKMattribString (VARIABLE_NAME (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/** <!--******************************************************************-->
 *
 * @fn CHKMwhile
 *
 * @brief Touched the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
CHKMwhile (node * arg_node, info * arg_info)
{
  DBUG_ENTER ("CHKMwhile");
  NODE_ERROR (arg_node) = CHKMTRAV (NODE_ERROR (arg_node), arg_info);
  WHILE_CONDITION (arg_node) =
    CHKMTRAV (WHILE_CONDITION (arg_node), arg_info);
  WHILE_BODY (arg_node) = CHKMTRAV (WHILE_BODY (arg_node), arg_info);
  DBUG_RETURN (arg_node);
}

/**
 * @}
 */
