
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ASSIGN_NAME (result) = STRcpy (ASSIGN_NAME (arg_node));
  /* Copy sons */
  ASSIGN_EXPRESSION (result) =
    COPYTRAV (ASSIGN_EXPRESSION (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OPERATOR (result) = BINOP_OPERATOR (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Block node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeBlock (NULL, NULL);
  DBUG_ENTER ("COPYblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  BLOCK_THIS (result) = COPYTRAV (BLOCK_THIS (arg_node), arg_info);
  BLOCK_NEXT (result) = COPYTRAV (BLOCK_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYboolconst
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BoolConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYboolconst (node * arg_node, info * arg_info)
{
  node *result = TBmakeBoolconst (FALSE);
  DBUG_ENTER ("COPYboolconst");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOLCONST_VALUE (result) = BOOLCONST_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYcast
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYcast (node * arg_node, info * arg_info)
{
  node *result = TBmakeCast (T_unknown, NULL);
  DBUG_ENTER ("COPYcast");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  CAST_TYPE (result) = CAST_TYPE (arg_node);
  /* Copy sons */
  CAST_EXPRESSION (result) = COPYTRAV (CAST_EXPRESSION (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdecblock
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DecBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdecblock (node * arg_node, info * arg_info)
{
  node *result = TBmakeDecblock (NULL, NULL);
  DBUG_ENTER ("COPYdecblock");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DECBLOCK_THIS (result) = COPYTRAV (DECBLOCK_THIS (arg_node), arg_info);
  DECBLOCK_NEXT (result) = COPYTRAV (DECBLOCK_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYdowhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYdowhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeDowhile (NULL, NULL);
  DBUG_ENTER ("COPYdowhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  DOWHILE_CONDITION (result) =
    COPYTRAV (DOWHILE_CONDITION (arg_node), arg_info);
  DOWHILE_BODY (result) = COPYTRAV (DOWHILE_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloatconst
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FloatConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloatconst (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloatconst (0.0);
  DBUG_ENTER ("COPYfloatconst");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOATCONST_VALUE (result) = FLOATCONST_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfor
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfor (node * arg_node, info * arg_info)
{
  node *result = TBmakeFor (NULL, NULL, NULL, NULL);
  DBUG_ENTER ("COPYfor");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FOR_START (result) = COPYTRAV (FOR_START (arg_node), arg_info);
  FOR_STOP (result) = COPYTRAV (FOR_STOP (arg_node), arg_info);
  FOR_STEP (result) = COPYTRAV (FOR_STEP (arg_node), arg_info);
  FOR_BODY (result) = COPYTRAV (FOR_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunargs
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunArgs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunargs (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunargs (NULL, NULL);
  DBUG_ENTER ("COPYfunargs");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNARGS_THIS (result) = COPYTRAV (FUNARGS_THIS (arg_node), arg_info);
  FUNARGS_NEXT (result) = COPYTRAV (FUNARGS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunbody
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunbody (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunbody (NULL, NULL);
  DBUG_ENTER ("COPYfunbody");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNBODY_DECLARATIONS (result) =
    COPYTRAV (FUNBODY_DECLARATIONS (arg_node), arg_info);
  FUNBODY_STATEMENTS (result) =
    COPYTRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfuncall
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfuncall (node * arg_node, info * arg_info)
{
  node *result = TBmakeFuncall (NULL, NULL);
  DBUG_ENTER ("COPYfuncall");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNCALL_NAME (result) = STRcpy (FUNCALL_NAME (arg_node));
  /* Copy sons */
  FUNCALL_ARGS (result) = COPYTRAV (FUNCALL_ARGS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfundec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfundec (node * arg_node, info * arg_info)
{
  node *result = TBmakeFundec (NULL, NULL, NULL);
  DBUG_ENTER ("COPYfundec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNDEC_NAME (result) = STRcpy (FUNDEC_NAME (arg_node));
  /* Copy sons */
  FUNDEC_PARAMS (result) = COPYTRAV (FUNDEC_PARAMS (arg_node), arg_info);
  FUNDEC_BODY (result) = COPYTRAV (FUNDEC_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunparam
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunParam node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunparam (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunparam (NULL, T_unknown);
  DBUG_ENTER ("COPYfunparam");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FUNPARAM_NAME (result) = STRcpy (FUNPARAM_NAME (arg_node));
  FUNPARAM_TYPE (result) = FUNPARAM_TYPE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfunparams
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node FunParams node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfunparams (node * arg_node, info * arg_info)
{
  node *result = TBmakeFunparams (NULL, NULL);
  DBUG_ENTER ("COPYfunparams");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  FUNPARAMS_THIS (result) = COPYTRAV (FUNPARAMS_THIS (arg_node), arg_info);
  FUNPARAMS_NEXT (result) = COPYTRAV (FUNPARAMS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYif
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYif (node * arg_node, info * arg_info)
{
  node *result = TBmakeIf (NULL, NULL, NULL);
  DBUG_ENTER ("COPYif");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  IF_CONDITION (result) = COPYTRAV (IF_CONDITION (arg_node), arg_info);
  IF_THEN (result) = COPYTRAV (IF_THEN (arg_node), arg_info);
  IF_ELSE (result) = COPYTRAV (IF_ELSE (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYintconst
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node IntConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYintconst (node * arg_node, info * arg_info)
{
  node *result = TBmakeIntconst (0);
  DBUG_ENTER ("COPYintconst");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  INTCONST_VALUE (result) = INTCONST_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmodule
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmodule (node * arg_node, info * arg_info)
{
  node *result = TBmakeModule (NULL, NULL);
  DBUG_ENTER ("COPYmodule");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MODULE_NAME (result) = STRcpy (MODULE_NAME (arg_node));
  /* Copy sons */
  MODULE_DECLARATIONS (result) =
    COPYTRAV (MODULE_DECLARATIONS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmonop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmonop (node * arg_node, info * arg_info)
{
  node *result = TBmakeMonop (MO_unknown, NULL);
  DBUG_ENTER ("COPYmonop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MONOP_OPERATOR (result) = MONOP_OPERATOR (arg_node);
  /* Copy sons */
  MONOP_OPERAND (result) = COPYTRAV (MONOP_OPERAND (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYproccall
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node ProcCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYproccall (node * arg_node, info * arg_info)
{
  node *result = TBmakeProccall (NULL, NULL);
  DBUG_ENTER ("COPYproccall");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  PROCCALL_NAME (result) = STRcpy (PROCCALL_NAME (arg_node));
  /* Copy sons */
  PROCCALL_ARGS (result) = COPYTRAV (PROCCALL_ARGS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYreturn
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYreturn (node * arg_node, info * arg_info)
{
  node *result = TBmakeReturn (NULL);
  DBUG_ENTER ("COPYreturn");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  RETURN_EXPRESSION (result) =
    COPYTRAV (RETURN_EXPRESSION (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvardec
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvardec (node * arg_node, info * arg_info)
{
  node *result = TBmakeVardec (NULL, NULL);
  DBUG_ENTER ("COPYvardec");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARDEC_NAME (result) = STRcpy (VARDEC_NAME (arg_node));
  /* Copy sons */
  VARDEC_EXPRESSION (result) =
    COPYTRAV (VARDEC_EXPRESSION (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvariable
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Variable node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvariable (node * arg_node, info * arg_info)
{
  node *result = TBmakeVariable (NULL);
  DBUG_ENTER ("COPYvariable");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARIABLE_NAME (result) = STRcpy (VARIABLE_NAME (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYwhile
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYwhile (node * arg_node, info * arg_info)
{
  node *result = TBmakeWhile (NULL, NULL);
  DBUG_ENTER ("COPYwhile");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  WHILE_CONDITION (result) = COPYTRAV (WHILE_CONDITION (arg_node), arg_info);
  WHILE_BODY (result) = COPYTRAV (WHILE_BODY (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
