
/**
 * @file free_node.c
 *
 * Functions needed by free traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: free_node.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup free Free Tree Functions.
 *
 * Functions needed by free traversal.
 *
 * @{
 */


#include "free.h"
#include "free_node.h"
#include "free_attribs.h"
#include "free_info.h"
#include "tree_basic.h"
#include "traverse.h"
#include "str.h"
#include "memory.h"
#include "dbug.h"

#define FREETRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node
#define FREECOND( node, info)                                    \
  (INFO_FREE_FLAG( info) != arg_node)                            \
    ? FREETRAV( node, info)                                      \
    : (node)


/** <!--******************************************************************-->
 *
 * @fn FREEassign
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEassign (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEassign");
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  ASSIGN_NAME (arg_node) =
    FREEattribString (ASSIGN_NAME (arg_node), arg_node);
  ASSIGN_EXPRESSION (arg_node) =
    FREETRAV (ASSIGN_EXPRESSION (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_assign = MEMfree (arg_node->sons.N_assign);
  arg_node->attribs.N_assign = MEMfree (arg_node->attribs.N_assign);
  DBUG_PRINT ("FREE", ("Processing node N_assign at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEbinop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEbinop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEbinop");
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  BINOP_LEFT (arg_node) = FREETRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (arg_node) = FREETRAV (BINOP_RIGHT (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_binop = MEMfree (arg_node->sons.N_binop);
  arg_node->attribs.N_binop = MEMfree (arg_node->attribs.N_binop);
  DBUG_PRINT ("FREE", ("Processing node N_binop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEblock
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Block node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEblock (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEblock");
  DBUG_PRINT ("FREE", ("Processing node N_block at " F_PTR, arg_node));
  BLOCK_NEXT (arg_node) = FREECOND (BLOCK_NEXT (arg_node), arg_info);
  BLOCK_THIS (arg_node) = FREETRAV (BLOCK_THIS (arg_node), arg_info);
  result = BLOCK_NEXT (arg_node);
  arg_node->sons.N_block = MEMfree (arg_node->sons.N_block);
  arg_node->attribs.N_block = MEMfree (arg_node->attribs.N_block);
  DBUG_PRINT ("FREE", ("Processing node N_block at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEboolconst
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node BoolConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEboolconst (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEboolconst");
  DBUG_PRINT ("FREE", ("Processing node N_boolconst at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_boolconst = MEMfree (arg_node->sons.N_boolconst);
  arg_node->attribs.N_boolconst = MEMfree (arg_node->attribs.N_boolconst);
  DBUG_PRINT ("FREE", ("Processing node N_boolconst at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEcast
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Cast node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEcast (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEcast");
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  CAST_EXPRESSION (arg_node) =
    FREETRAV (CAST_EXPRESSION (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_cast = MEMfree (arg_node->sons.N_cast);
  arg_node->attribs.N_cast = MEMfree (arg_node->attribs.N_cast);
  DBUG_PRINT ("FREE", ("Processing node N_cast at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdecblock
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DecBlock node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdecblock (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdecblock");
  DBUG_PRINT ("FREE", ("Processing node N_decblock at " F_PTR, arg_node));
  DECBLOCK_NEXT (arg_node) = FREECOND (DECBLOCK_NEXT (arg_node), arg_info);
  DECBLOCK_THIS (arg_node) = FREETRAV (DECBLOCK_THIS (arg_node), arg_info);
  result = DECBLOCK_NEXT (arg_node);
  arg_node->sons.N_decblock = MEMfree (arg_node->sons.N_decblock);
  arg_node->attribs.N_decblock = MEMfree (arg_node->attribs.N_decblock);
  DBUG_PRINT ("FREE", ("Processing node N_decblock at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEdowhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node DoWhile node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEdowhile (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEdowhile");
  DBUG_PRINT ("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
  DOWHILE_CONDITION (arg_node) =
    FREETRAV (DOWHILE_CONDITION (arg_node), arg_info);
  DOWHILE_BODY (arg_node) = FREETRAV (DOWHILE_BODY (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_dowhile = MEMfree (arg_node->sons.N_dowhile);
  arg_node->attribs.N_dowhile = MEMfree (arg_node->attribs.N_dowhile);
  DBUG_PRINT ("FREE", ("Processing node N_dowhile at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfloatconst
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FloatConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfloatconst (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfloatconst");
  DBUG_PRINT ("FREE", ("Processing node N_floatconst at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_floatconst = MEMfree (arg_node->sons.N_floatconst);
  arg_node->attribs.N_floatconst = MEMfree (arg_node->attribs.N_floatconst);
  DBUG_PRINT ("FREE", ("Processing node N_floatconst at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfor
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node For node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfor (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfor");
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  FOR_START (arg_node) = FREETRAV (FOR_START (arg_node), arg_info);
  FOR_STOP (arg_node) = FREETRAV (FOR_STOP (arg_node), arg_info);
  FOR_STEP (arg_node) = FREETRAV (FOR_STEP (arg_node), arg_info);
  FOR_BODY (arg_node) = FREETRAV (FOR_BODY (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_for = MEMfree (arg_node->sons.N_for);
  arg_node->attribs.N_for = MEMfree (arg_node->attribs.N_for);
  DBUG_PRINT ("FREE", ("Processing node N_for at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunargs
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunArgs node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunargs (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunargs");
  DBUG_PRINT ("FREE", ("Processing node N_funargs at " F_PTR, arg_node));
  FUNARGS_NEXT (arg_node) = FREECOND (FUNARGS_NEXT (arg_node), arg_info);
  FUNARGS_THIS (arg_node) = FREETRAV (FUNARGS_THIS (arg_node), arg_info);
  result = FUNARGS_NEXT (arg_node);
  arg_node->sons.N_funargs = MEMfree (arg_node->sons.N_funargs);
  arg_node->attribs.N_funargs = MEMfree (arg_node->attribs.N_funargs);
  DBUG_PRINT ("FREE", ("Processing node N_funargs at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunbody
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunBody node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunbody (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunbody");
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  FUNBODY_DECLARATIONS (arg_node) =
    FREETRAV (FUNBODY_DECLARATIONS (arg_node), arg_info);
  FUNBODY_STATEMENTS (arg_node) =
    FREETRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funbody = MEMfree (arg_node->sons.N_funbody);
  arg_node->attribs.N_funbody = MEMfree (arg_node->attribs.N_funbody);
  DBUG_PRINT ("FREE", ("Processing node N_funbody at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfuncall
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfuncall (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfuncall");
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  FUNCALL_NAME (arg_node) =
    FREEattribString (FUNCALL_NAME (arg_node), arg_node);
  FUNCALL_ARGS (arg_node) = FREETRAV (FUNCALL_ARGS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_funcall = MEMfree (arg_node->sons.N_funcall);
  arg_node->attribs.N_funcall = MEMfree (arg_node->attribs.N_funcall);
  DBUG_PRINT ("FREE", ("Processing node N_funcall at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfundec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfundec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfundec");
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  FUNDEC_NAME (arg_node) =
    FREEattribString (FUNDEC_NAME (arg_node), arg_node);
  FUNDEC_PARAMS (arg_node) = FREETRAV (FUNDEC_PARAMS (arg_node), arg_info);
  FUNDEC_BODY (arg_node) = FREETRAV (FUNDEC_BODY (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_fundec = MEMfree (arg_node->sons.N_fundec);
  arg_node->attribs.N_fundec = MEMfree (arg_node->attribs.N_fundec);
  DBUG_PRINT ("FREE", ("Processing node N_fundec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunparam
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunParam node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunparam (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunparam");
  DBUG_PRINT ("FREE", ("Processing node N_funparam at " F_PTR, arg_node));
  FUNPARAM_NAME (arg_node) =
    FREEattribString (FUNPARAM_NAME (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_funparam = MEMfree (arg_node->sons.N_funparam);
  arg_node->attribs.N_funparam = MEMfree (arg_node->attribs.N_funparam);
  DBUG_PRINT ("FREE", ("Processing node N_funparam at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEfunparams
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node FunParams node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEfunparams (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEfunparams");
  DBUG_PRINT ("FREE", ("Processing node N_funparams at " F_PTR, arg_node));
  FUNPARAMS_NEXT (arg_node) = FREECOND (FUNPARAMS_NEXT (arg_node), arg_info);
  FUNPARAMS_THIS (arg_node) = FREETRAV (FUNPARAMS_THIS (arg_node), arg_info);
  result = FUNPARAMS_NEXT (arg_node);
  arg_node->sons.N_funparams = MEMfree (arg_node->sons.N_funparams);
  arg_node->attribs.N_funparams = MEMfree (arg_node->attribs.N_funparams);
  DBUG_PRINT ("FREE", ("Processing node N_funparams at " F_PTR, arg_node));
  arg_node = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEif
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node If node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEif (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEif");
  DBUG_PRINT ("FREE", ("Processing node N_if at " F_PTR, arg_node));
  IF_CONDITION (arg_node) = FREETRAV (IF_CONDITION (arg_node), arg_info);
  IF_THEN (arg_node) = FREETRAV (IF_THEN (arg_node), arg_info);
  IF_ELSE (arg_node) = FREETRAV (IF_ELSE (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_if = MEMfree (arg_node->sons.N_if);
  arg_node->attribs.N_if = MEMfree (arg_node->attribs.N_if);
  DBUG_PRINT ("FREE", ("Processing node N_if at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEintconst
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node IntConst node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEintconst (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEintconst");
  DBUG_PRINT ("FREE", ("Processing node N_intconst at " F_PTR, arg_node));
  result = NULL;
  arg_node->sons.N_intconst = MEMfree (arg_node->sons.N_intconst);
  arg_node->attribs.N_intconst = MEMfree (arg_node->attribs.N_intconst);
  DBUG_PRINT ("FREE", ("Processing node N_intconst at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEmodule
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEmodule (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEmodule");
  DBUG_PRINT ("FREE", ("Processing node N_module at " F_PTR, arg_node));
  MODULE_NAME (arg_node) =
    FREEattribString (MODULE_NAME (arg_node), arg_node);
  MODULE_DECLARATIONS (arg_node) =
    FREETRAV (MODULE_DECLARATIONS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_module = MEMfree (arg_node->sons.N_module);
  arg_node->attribs.N_module = MEMfree (arg_node->attribs.N_module);
  DBUG_PRINT ("FREE", ("Processing node N_module at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEmonop
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node MonOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEmonop (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEmonop");
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  MONOP_OPERAND (arg_node) = FREETRAV (MONOP_OPERAND (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_monop = MEMfree (arg_node->sons.N_monop);
  arg_node->attribs.N_monop = MEMfree (arg_node->attribs.N_monop);
  DBUG_PRINT ("FREE", ("Processing node N_monop at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEproccall
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node ProcCall node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEproccall (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEproccall");
  DBUG_PRINT ("FREE", ("Processing node N_proccall at " F_PTR, arg_node));
  PROCCALL_NAME (arg_node) =
    FREEattribString (PROCCALL_NAME (arg_node), arg_node);
  PROCCALL_ARGS (arg_node) = FREETRAV (PROCCALL_ARGS (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_proccall = MEMfree (arg_node->sons.N_proccall);
  arg_node->attribs.N_proccall = MEMfree (arg_node->attribs.N_proccall);
  DBUG_PRINT ("FREE", ("Processing node N_proccall at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEreturn
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Return node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEreturn (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEreturn");
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  RETURN_EXPRESSION (arg_node) =
    FREETRAV (RETURN_EXPRESSION (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_return = MEMfree (arg_node->sons.N_return);
  arg_node->attribs.N_return = MEMfree (arg_node->attribs.N_return);
  DBUG_PRINT ("FREE", ("Processing node N_return at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvardec
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node VarDec node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvardec (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvardec");
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  VARDEC_NAME (arg_node) =
    FREEattribString (VARDEC_NAME (arg_node), arg_node);
  VARDEC_EXPRESSION (arg_node) =
    FREETRAV (VARDEC_EXPRESSION (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_vardec = MEMfree (arg_node->sons.N_vardec);
  arg_node->attribs.N_vardec = MEMfree (arg_node->attribs.N_vardec);
  DBUG_PRINT ("FREE", ("Processing node N_vardec at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEvariable
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node Variable node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEvariable (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEvariable");
  DBUG_PRINT ("FREE", ("Processing node N_variable at " F_PTR, arg_node));
  VARIABLE_NAME (arg_node) =
    FREEattribString (VARIABLE_NAME (arg_node), arg_node);
  result = NULL;
  arg_node->sons.N_variable = MEMfree (arg_node->sons.N_variable);
  arg_node->attribs.N_variable = MEMfree (arg_node->attribs.N_variable);
  DBUG_PRINT ("FREE", ("Processing node N_variable at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn FREEwhile
 *
 * @brief Frees the node and its sons/attributes
 *
 * @param arg_node While node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
FREEwhile (node * arg_node, info * arg_info)
{
  node *result = NULL;
  DBUG_ENTER ("FREEwhile");
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  WHILE_CONDITION (arg_node) =
    FREETRAV (WHILE_CONDITION (arg_node), arg_info);
  WHILE_BODY (arg_node) = FREETRAV (WHILE_BODY (arg_node), arg_info);
  result = NULL;
  arg_node->sons.N_while = MEMfree (arg_node->sons.N_while);
  arg_node->attribs.N_while = MEMfree (arg_node->attribs.N_while);
  DBUG_PRINT ("FREE", ("Processing node N_while at " F_PTR, arg_node));
  result = MEMfree (arg_node);
  DBUG_RETURN (result);
}

/**
 * @}
 */
