
/**
 * @file traverse_tables.c
 *
 * This file defines the function tables for traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_tables.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#include "traverse_tables.h"
#include "traverse_helper.h"
#include "print.h"
#include "copy_node.h"
#include "free_node.h"
#include "check.h"
#include "rename_identifiers.h"
#include "sum_ints.h"
#include "opt_sub.h"
#include "strength_reduction.h"
#include "count_ops.h"
#include "count_ids.h"


travtables_t travtables = {
  /* TR_undefined */
  {&TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror, &TRAVerror,
   &TRAVerror}

  /* TR_prt */
  , {&TRAVerror, &PRTmodule, &PRTdecblock, &PRTfundec, &PRTfunparams,
     &PRTfunparam, &PRTfunbody, &PRTvardec, &PRTblock, &PRTassign,
     &PRTproccall, &PRTif, &PRTwhile, &PRTdowhile, &PRTfor, &PRTreturn,
     &PRTbinop, &PRTmonop, &PRTcast, &PRTfuncall, &PRTfunargs, &PRTvariable,
     &PRTintconst, &PRTfloatconst, &PRTboolconst}

  /* TR_copy */
  , {&TRAVerror, &COPYmodule, &COPYdecblock, &COPYfundec, &COPYfunparams,
     &COPYfunparam, &COPYfunbody, &COPYvardec, &COPYblock, &COPYassign,
     &COPYproccall, &COPYif, &COPYwhile, &COPYdowhile, &COPYfor, &COPYreturn,
     &COPYbinop, &COPYmonop, &COPYcast, &COPYfuncall, &COPYfunargs,
     &COPYvariable, &COPYintconst, &COPYfloatconst, &COPYboolconst}

  /* TR_free */
  , {&TRAVerror, &FREEmodule, &FREEdecblock, &FREEfundec, &FREEfunparams,
     &FREEfunparam, &FREEfunbody, &FREEvardec, &FREEblock, &FREEassign,
     &FREEproccall, &FREEif, &FREEwhile, &FREEdowhile, &FREEfor, &FREEreturn,
     &FREEbinop, &FREEmonop, &FREEcast, &FREEfuncall, &FREEfunargs,
     &FREEvariable, &FREEintconst, &FREEfloatconst, &FREEboolconst}

  /* TR_chk */
  , {&TRAVerror, &CHKmodule, &CHKdecblock, &CHKfundec, &CHKfunparams,
     &CHKfunparam, &CHKfunbody, &CHKvardec, &CHKblock, &CHKassign,
     &CHKproccall, &CHKif, &CHKwhile, &CHKdowhile, &CHKfor, &CHKreturn,
     &CHKbinop, &CHKmonop, &CHKcast, &CHKfuncall, &CHKfunargs, &CHKvariable,
     &CHKintconst, &CHKfloatconst, &CHKboolconst}

  /* TR_ri */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_si */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_os */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &OSbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_sr */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &SRbinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_co */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &CObinop, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}

  /* TR_ci */
  , {&TRAVerror, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons, &TRAVsons,
     &TRAVsons}
};

preposttable_t pretable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

preposttable_t posttable = {
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

const char *travnames[11] = {
  "unknown", "prt", "copy", "free", "chk", "ri", "si", "os", "sr", "co", "ci"
};
