
/**
 * @file traverse_helper.c
 *
 * Defines the helper function needed by the traversal system
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: traverse_helper.c.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */


#include "traverse_helper.h"
#include "dbug.h"
#include "tree_basic.h"
#include "traverse.h"

#define TRAV( son, info)    if (son != NULL) { son = TRAVdo( son, info); }

node *
TRAVnone (node * arg_node, info * arg_info)
{
  return (arg_node);
}

node *
TRAVerror (node * arg_node, info * arg_info)
{
  DBUG_ASSERT ((FALSE), "Illegal node type found.");

  return (arg_node);
}

node *
TRAVsons (node * arg_node, info * arg_info)
{
  switch (NODE_TYPE (arg_node))
    {
    case N_module:
      TRAV (MODULE_DECLARATIONS (arg_node), arg_info);
      break;
    case N_decblock:
      TRAV (DECBLOCK_THIS (arg_node), arg_info);
      TRAV (DECBLOCK_NEXT (arg_node), arg_info);
      break;
    case N_fundec:
      TRAV (FUNDEC_PARAMS (arg_node), arg_info);
      TRAV (FUNDEC_BODY (arg_node), arg_info);
      break;
    case N_funparams:
      TRAV (FUNPARAMS_THIS (arg_node), arg_info);
      TRAV (FUNPARAMS_NEXT (arg_node), arg_info);
      break;
    case N_funparam:
      break;
    case N_funbody:
      TRAV (FUNBODY_DECLARATIONS (arg_node), arg_info);
      TRAV (FUNBODY_STATEMENTS (arg_node), arg_info);
      break;
    case N_vardec:
      TRAV (VARDEC_EXPRESSION (arg_node), arg_info);
      break;
    case N_block:
      TRAV (BLOCK_THIS (arg_node), arg_info);
      TRAV (BLOCK_NEXT (arg_node), arg_info);
      break;
    case N_assign:
      TRAV (ASSIGN_EXPRESSION (arg_node), arg_info);
      break;
    case N_proccall:
      TRAV (PROCCALL_ARGS (arg_node), arg_info);
      break;
    case N_if:
      TRAV (IF_CONDITION (arg_node), arg_info);
      TRAV (IF_THEN (arg_node), arg_info);
      TRAV (IF_ELSE (arg_node), arg_info);
      break;
    case N_while:
      TRAV (WHILE_CONDITION (arg_node), arg_info);
      TRAV (WHILE_BODY (arg_node), arg_info);
      break;
    case N_dowhile:
      TRAV (DOWHILE_CONDITION (arg_node), arg_info);
      TRAV (DOWHILE_BODY (arg_node), arg_info);
      break;
    case N_for:
      TRAV (FOR_START (arg_node), arg_info);
      TRAV (FOR_STOP (arg_node), arg_info);
      TRAV (FOR_STEP (arg_node), arg_info);
      TRAV (FOR_BODY (arg_node), arg_info);
      break;
    case N_return:
      TRAV (RETURN_EXPRESSION (arg_node), arg_info);
      break;
    case N_binop:
      TRAV (BINOP_LEFT (arg_node), arg_info);
      TRAV (BINOP_RIGHT (arg_node), arg_info);
      break;
    case N_monop:
      TRAV (MONOP_OPERAND (arg_node), arg_info);
      break;
    case N_cast:
      TRAV (CAST_EXPRESSION (arg_node), arg_info);
      break;
    case N_funcall:
      TRAV (FUNCALL_ARGS (arg_node), arg_info);
      break;
    case N_funargs:
      TRAV (FUNARGS_THIS (arg_node), arg_info);
      TRAV (FUNARGS_NEXT (arg_node), arg_info);
      break;
    case N_variable:
      break;
    case N_intconst:
      break;
    case N_floatconst:
      break;
    case N_boolconst:
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  return (arg_node);
}

int
TRAVnumSons (node * node)
{
  int result = 0;

  DBUG_ENTER ("TRAVnumSons");

  switch (NODE_TYPE (node))
    {
    case N_module:
      result = 1;
      break;
    case N_decblock:
      result = 2;
      break;
    case N_fundec:
      result = 2;
      break;
    case N_funparams:
      result = 2;
      break;
    case N_funparam:
      result = 0;
      break;
    case N_funbody:
      result = 2;
      break;
    case N_vardec:
      result = 1;
      break;
    case N_block:
      result = 2;
      break;
    case N_assign:
      result = 1;
      break;
    case N_proccall:
      result = 1;
      break;
    case N_if:
      result = 3;
      break;
    case N_while:
      result = 2;
      break;
    case N_dowhile:
      result = 2;
      break;
    case N_for:
      result = 4;
      break;
    case N_return:
      result = 1;
      break;
    case N_binop:
      result = 2;
      break;
    case N_monop:
      result = 1;
      break;
    case N_cast:
      result = 1;
      break;
    case N_funcall:
      result = 1;
      break;
    case N_funargs:
      result = 2;
      break;
    case N_variable:
      result = 0;
      break;
    case N_intconst:
      result = 0;
      break;
    case N_floatconst:
      result = 0;
      break;
    case N_boolconst:
      result = 0;
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}

node *
TRAVgetSon (int no, node * parent)
{
  node *result = NULL;

  DBUG_ENTER ("TRAVgetSon");

  switch (NODE_TYPE (parent))
    {
    case N_module:
      switch (no)
	{
	case 0:
	  result = MODULE_DECLARATIONS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_decblock:
      switch (no)
	{
	case 0:
	  result = DECBLOCK_THIS (parent);
	  break;
	case 1:
	  result = DECBLOCK_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_fundec:
      switch (no)
	{
	case 0:
	  result = FUNDEC_PARAMS (parent);
	  break;
	case 1:
	  result = FUNDEC_BODY (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funparams:
      switch (no)
	{
	case 0:
	  result = FUNPARAMS_THIS (parent);
	  break;
	case 1:
	  result = FUNPARAMS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funparam:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funbody:
      switch (no)
	{
	case 0:
	  result = FUNBODY_DECLARATIONS (parent);
	  break;
	case 1:
	  result = FUNBODY_STATEMENTS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_vardec:
      switch (no)
	{
	case 0:
	  result = VARDEC_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_block:
      switch (no)
	{
	case 0:
	  result = BLOCK_THIS (parent);
	  break;
	case 1:
	  result = BLOCK_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_assign:
      switch (no)
	{
	case 0:
	  result = ASSIGN_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_proccall:
      switch (no)
	{
	case 0:
	  result = PROCCALL_ARGS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_if:
      switch (no)
	{
	case 0:
	  result = IF_CONDITION (parent);
	  break;
	case 1:
	  result = IF_THEN (parent);
	  break;
	case 2:
	  result = IF_ELSE (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_while:
      switch (no)
	{
	case 0:
	  result = WHILE_CONDITION (parent);
	  break;
	case 1:
	  result = WHILE_BODY (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_dowhile:
      switch (no)
	{
	case 0:
	  result = DOWHILE_CONDITION (parent);
	  break;
	case 1:
	  result = DOWHILE_BODY (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_for:
      switch (no)
	{
	case 0:
	  result = FOR_START (parent);
	  break;
	case 1:
	  result = FOR_STOP (parent);
	  break;
	case 2:
	  result = FOR_STEP (parent);
	  break;
	case 3:
	  result = FOR_BODY (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_return:
      switch (no)
	{
	case 0:
	  result = RETURN_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_binop:
      switch (no)
	{
	case 0:
	  result = BINOP_LEFT (parent);
	  break;
	case 1:
	  result = BINOP_RIGHT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_monop:
      switch (no)
	{
	case 0:
	  result = MONOP_OPERAND (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_cast:
      switch (no)
	{
	case 0:
	  result = CAST_EXPRESSION (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funcall:
      switch (no)
	{
	case 0:
	  result = FUNCALL_ARGS (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_funargs:
      switch (no)
	{
	case 0:
	  result = FUNARGS_THIS (parent);
	  break;
	case 1:
	  result = FUNARGS_NEXT (parent);
	  break;
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_variable:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_intconst:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_floatconst:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    case N_boolconst:
      switch (no)
	{
	default:
	  DBUG_ASSERT ((FALSE), "index out of range!");
	  break;
	}
      break;
    default:
      DBUG_ASSERT ((FALSE), "Illegal nodetype found!");
      break;
    }

  DBUG_RETURN (result);
}
