
/**
 * @file types_trav.h
 *
 * This file defines the trav_t phase enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_trav.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_TRAV_H_
#define _SAC_TYPES_TRAV_H_

typedef enum
{ TR_undefined = 0, TR_prt = 1, TR_copy = 2, TR_free = 3, TR_chk = 4, TR_ri =
    5, TR_si = 6, TR_os = 7, TR_sr = 8, TR_co = 9, TR_ci = 10 } trav_t;
#endif /* _SAC_TYPES_TRAV_H_ */
