
/**
 * @file copy_node.c
 *
 * Functions needed by copy traversal.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * copy_node.c.xsl.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

/**
 * @defgroup copy Copy Tree Functions.
 *
 * Functions needed by copy traversal.
 *
 * @{
 */


#include "copy_node.h"
#include "copy_info.h"
#include "traverse.h"
#include "dbug.h"
#include "tree_basic.h"
#include "str.h"
#include "lookup_table.h"


#define COPYTRAV( node, info) (node != NULL) ? TRAVdo( node, info) : node


/** <!--******************************************************************-->
 *
 * @fn COPYassign
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Assign node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYassign (node * arg_node, info * arg_info)
{
  node *result = TBmakeAssign (NULL, NULL);
  DBUG_ENTER ("COPYassign");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  ASSIGN_LET (result) = COPYTRAV (ASSIGN_LET (arg_node), arg_info);
  ASSIGN_EXPR (result) = COPYTRAV (ASSIGN_EXPR (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbinop
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node BinOp node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbinop (node * arg_node, info * arg_info)
{
  node *result = TBmakeBinop (BO_unknown, NULL, NULL);
  DBUG_ENTER ("COPYbinop");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BINOP_OP (result) = BINOP_OP (arg_node);
  /* Copy sons */
  BINOP_LEFT (result) = COPYTRAV (BINOP_LEFT (arg_node), arg_info);
  BINOP_RIGHT (result) = COPYTRAV (BINOP_RIGHT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYbool
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Bool node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYbool (node * arg_node, info * arg_info)
{
  node *result = TBmakeBool (FALSE);
  DBUG_ENTER ("COPYbool");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  BOOL_VALUE (result) = BOOL_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYerror
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Error node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYerror (node * arg_node, info * arg_info)
{
  node *result = TBmakeError (NULL, PH_initial, NULL);
  DBUG_ENTER ("COPYerror");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  ERROR_MESSAGE (result) = STRcpy (ERROR_MESSAGE (arg_node));
  ERROR_ANYPHASE (result) = ERROR_ANYPHASE (arg_node);
  /* Copy sons */
  ERROR_NEXT (result) = COPYTRAV (ERROR_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYfloat
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Float node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYfloat (node * arg_node, info * arg_info)
{
  node *result = TBmakeFloat (0.0);
  DBUG_ENTER ("COPYfloat");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  FLOAT_VALUE (result) = FLOAT_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYmodule
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Module node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYmodule (node * arg_node, info * arg_info)
{
  node *result = TBmakeModule (0, 0, 0, 0, 0, NULL);
  DBUG_ENTER ("COPYmodule");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  MODULE_ADD_COUNT (result) = MODULE_ADD_COUNT (arg_node);
  MODULE_SUB_COUNT (result) = MODULE_SUB_COUNT (arg_node);
  MODULE_MUL_COUNT (result) = MODULE_MUL_COUNT (arg_node);
  MODULE_DIV_COUNT (result) = MODULE_DIV_COUNT (arg_node);
  MODULE_MOD_COUNT (result) = MODULE_MOD_COUNT (arg_node);
  /* Copy sons */
  MODULE_STMTS (result) = COPYTRAV (MODULE_STMTS (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYnum
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Num node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYnum (node * arg_node, info * arg_info)
{
  node *result = TBmakeNum (0);
  DBUG_ENTER ("COPYnum");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  NUM_VALUE (result) = NUM_VALUE (arg_node);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYstmts
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Stmts node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYstmts (node * arg_node, info * arg_info)
{
  node *result = TBmakeStmts (NULL, NULL);
  DBUG_ENTER ("COPYstmts");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy sons */
  STMTS_STMT (result) = COPYTRAV (STMTS_STMT (arg_node), arg_info);
  STMTS_NEXT (result) = COPYTRAV (STMTS_NEXT (arg_node), arg_info);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYsymboltableentry
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node SymbolTableEntry node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYsymboltableentry (node * arg_node, info * arg_info)
{
  node *result = TBmakeSymboltableentry ();
  DBUG_ENTER ("COPYsymboltableentry");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvar
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node Var node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvar (node * arg_node, info * arg_info)
{
  node *result = TBmakeVar (NULL);
  DBUG_ENTER ("COPYvar");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VAR_NAME (result) = STRcpy (VAR_NAME (arg_node));
  VAR_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VAR_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/** <!--******************************************************************-->
 *
 * @fn COPYvarlet
 *
 * @brief Copies the node and its sons/attributes
 *
 * @param arg_node VarLet node to process
 * @param arg_info pointer to info structure
 *
 * @return processed node
 *
 ***************************************************************************/
node *
COPYvarlet (node * arg_node, info * arg_info)
{
  node *result = TBmakeVarlet (NULL);
  DBUG_ENTER ("COPYvarlet");
  LUTinsertIntoLutP (INFO_LUT (arg_info), arg_node, result);
  /* Copy attributes */
  VARLET_NAME (result) = STRcpy (VARLET_NAME (arg_node));
  VARLET_DECL (result) =
    LUTsearchInLutPp (INFO_LUT (arg_info), VARLET_DECL (arg_node));
  /* Return value */
  DBUG_RETURN (result);
}

/**
 * @}
 */
