
/**
 * @file free_node.h
 *
 * Functions to free node structures
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: copy_node.h.xsl 296 2008-02-26 01:52:31Z sah $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_COPY_NODE_H_
#define _SAC_COPY_NODE_H_

#include "types.h"

extern node *COPYassign (node * arg_node, info * arg_info);
extern node *COPYbinop (node * arg_node, info * arg_info);
extern node *COPYbool (node * arg_node, info * arg_info);
extern node *COPYerror (node * arg_node, info * arg_info);
extern node *COPYfloat (node * arg_node, info * arg_info);
extern node *COPYmodule (node * arg_node, info * arg_info);
extern node *COPYnum (node * arg_node, info * arg_info);
extern node *COPYstmts (node * arg_node, info * arg_info);
extern node *COPYsymboltableentry (node * arg_node, info * arg_info);
extern node *COPYvar (node * arg_node, info * arg_info);
extern node *COPYvarlet (node * arg_node, info * arg_info);

#endif /* _SAC_COPY_NODE_H_ */
