
/**
 * @file types_nodetype.h
 *
 * This file defines the nodetype node enumeration.
 * 
 * THIS FILE HAS BEEN GENERATED USING 
 * $Id: types_nodetype.h.xsl 14593 2006-01-31 17:09:55Z cg $.
 * DO NOT EDIT THIS FILE AS MIGHT BE CHANGED IN A LATER VERSION.
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
 */

#ifndef _SAC_TYPES_NODETYPE_H_
#define _SAC_TYPES_NODETYPE_H_

#define MAX_NODES 11
typedef enum
{ N_undefined = 0, N_module = 1, N_stmts = 2, N_assign = 3, N_binop =
    4, N_varlet = 5, N_var = 6, N_num = 7, N_float = 8, N_bool =
    9, N_symboltableentry = 10, N_error = 11 } nodetype;

#endif /* _SAC_TYPES_NODETYPE_H_ */
